# Generated by Django 3.2.8 on 2021-10-19 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('devdo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='idea',
            name='in_progress',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='idea',
            name='poster',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
