# Generated by Django 3.2.8 on 2021-10-19 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('devdo', '0002_auto_20211019_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='dev',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dev', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='idea',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poster', to=settings.AUTH_USER_MODEL),
        ),
    ]
