# Generated by Django 3.2.8 on 2021-10-19 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('devdo', '0004_idea_user_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='dev',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dev', to=settings.AUTH_USER_MODEL),
        ),
    ]
