# Generated by Django 3.2.8 on 2021-10-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devdo', '0007_auto_20211021_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='tags',
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('ideas', models.ManyToManyField(blank=True, related_name='tags', to='devdo.Idea')),
            ],
        ),
    ]
